# Generated by Django 4.1.4 on 2023-03-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_courses_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='checkbox',
        ),
    ]
