# Generated by Django 4.1.4 on 2023-03-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_courses_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='checkbox',
            field=models.BooleanField(null=True),
        ),
    ]
