# Generated by Django 4.1.4 on 2023-03-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_courses_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
