# Generated by Django 4.1.4 on 2023-03-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='registered',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
